
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Oct 23 13:40:43 PET 2025
//----------------------------------------------------

package Cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Abrir = 2;
  public static final int MENOS = 13;
  public static final int Tiempo = 9;
  public static final int ERROR = 14;
  public static final int Apagar = 5;
  public static final int EOF = 0;
  public static final int MAS = 12;
  public static final int Cocinar = 8;
  public static final int error = 1;
  public static final int Encender = 4;
  public static final int Potencia = 6;
  public static final int DOS_PUNTOS = 11;
  public static final int Numero = 10;
  public static final int Cerrar = 3;
  public static final int Pausar = 7;
}

