
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sat Oct 25 14:22:32 GMT-05:00 2025
//----------------------------------------------------

package Cup;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Abrir = 7;
  public static final int MENOS = 5;
  public static final int Tiempo = 14;
  public static final int ERROR = 6;
  public static final int Apagar = 10;
  public static final int EOF = 0;
  public static final int MAS = 4;
  public static final int Cocinar = 13;
  public static final int error = 1;
  public static final int Encender = 9;
  public static final int Potencia = 11;
  public static final int DOS_PUNTOS = 3;
  public static final int Numero = 2;
  public static final int Pausar = 12;
  public static final int Cerrar = 8;
  public static final int Inicio = 15;
  public static final int Final = 16;
  public static final int Reanudar = 17;
}

